<?php
///////
//////MENU
//////
function shift_cipher_menu() {
  $items['shift_cipher'] = array(
    'title' => 'Shift Cipher',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('shift_cipher_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['shift_cipher_results_page'] = array(
    'title' => 'Results',
    'page callback' => 'shift_cipher_results',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}
////////
///////FORM
///////
function shift_cipher_form() {
  $form['shift_value'] = array(
    '#title' => 'Shift Value',
    '#type' => 'textfield',
    '#description' => t('Please input the number you want cipher to shift'),
    '#element_validate' => array(),
    // '#required' => TRUE,
  );

  $form['shift_direction'] = array(
    '#title' => 'Shift Direction',
    '#type' => 'textfield',
    '#description' => t('Please input the direction you want cipher to shift, right or left'),
    '#element_validate' => array(),
    // '#required' => TRUE,
  );

  $form['shift_message'] = array(
    '#title' => 'Message',
    '#type' => 'textfield',
    '#description' => t('Please input the message you want ciphered'),
    '#element_validate' => array(),
    '#required' => TRUE,
  );

  $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Go',
    );
  return $form;
}
////////
///////FORM SUBMIT
///////
function shift_cipher_form_submit($form, &$form_state) {
  $shift_value = $form_state['values']['shift_value'];
  $shift_direction = $form_state['values']['shift_direction'];
  $shift_message = $form_state['values']['shift_message'];

  $letter_values = array('a' => 0, 'b' => 1, 'c' => 2, 'd' => 3, 'e' => 4, 'f' => 5, 'g' => 6, 'h' => 7, 'i' => 8, 'j' => 9, 'k' => 10, 'l' => 11, 'm' => 12, 'n' => 13, 'o' => 14, 'p' => 15, 'q' => 16, 'r' => 17, 's' => 18, 't' => 19, 'u' => 20, 'v' => 21, 'w' => 22, 'x' => 23, 'y' => 24, 'z' => 25, ' ' => ' ');

  $number_values = array(0 => 'a', 1 => 'b', 2 => 'c', 3 => 'd', 4 => 'e', 5 => 'f', 6 => 'g', 7 => 'h', 8 => 'i', 9 => 'j', 10 => 'k', 11 => 'l', 12 => 'm', 13 => 'n', 14 => 'o', 15 => 'p', 16 => 'q', 17 => 'r', 18 => 's', 19 => 't', 20 => 'u', 21 => 'v', 22 => 'w', 23 => 'x', 24 => 'y', 25 => 'z', ' ' => ' ');

  $message_array = str_split(strtolower($shift_message));

  $num_array = array();
  $let_str = '';

  if(strtolower($shift_direction) === 'left') {
      foreach($message_array as $char) {
          $num_value = $letter_values[$char];
          if($num_value === ' ') {
              array_push($num_array, ' ');
          } else{
              $num_shift = (26 + $num_value - $shift_value) % 26;
              array_push($num_array, $num_shift);
          }
      }
     foreach($num_array as $char) {
         $letter_val = $number_values[$char];
         $let_str .= $letter_val;
     }
  }
  if(strtolower($shift_direction) === 'right') {
      foreach($message_array as $char) {
          $num_value = $letter_values[$char];
          if($num_value === ' ') {
              $num_str .= ' ';
          } else{
              $num_shift = (26 + $num_value + $shift_value) % 26;
              array_push($num_array, $num_shift);
          }
      }
     foreach($num_array as $char) {
         $letter_val = $number_values[$char];
         $let_str .= $letter_val;
     }
  }

  $result = $let_str;

  $_SESSION['shift_cipher_output'] = $result;
  $form_state['redirect'] = 'shift_cipher_results_page';
}

function shift_cipher_results() {
  $result_display = $_SESSION['shift_cipher_output'];
  var_dump($result_display);
  return $result_display;
}
